define("text!partials/_wedo2.html", [], function () {
    return '<div class="panel-status panel panel-default">\r\n    <div class="panel-body">\r\n      <div class="connection device-connection">\r\n        <div class="connected">WeDo 2.0 is connected</div>\r\n        <div class="not-connected">WeDo 2.0 is not connected</div>\r\n      </div>\r\n      <div class="connection scratch-connection">\r\n        <div class="connected">Scratch is connected</div>\r\n        <div class="not-connected">Scratch is not connected</div>\r\n      </div>\r\n      <div class="table-wrapper">\r\n        <table class="table">\r\n          <colgroup>\r\n            <col />\r\n            <col />\r\n            <col />\r\n          </colgroup>\r\n          <tbody>\r\n          </tbody>\r\n        </table>\r\n      </div>\r\n      <div class="req">\r\n        <div class="now-time"></div>\r\n        <div class="req-path"></div>\r\n        <div class="req-time"></div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n'
});
define("text!partials/_ble-search-dialog.html", [], function () {
    return '<div class="modal fade ble-search-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">\r\n  <div class="modal-dialog" role="document">\r\n    <div class="modal-content">\r\n      <div class="modal-header">\r\n        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>\r\n        <button type="button" data-toggle="tooltip" title="Reset" class="btn btn-default btn-small btn-reset">\r\n            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>\r\n        </button>\r\n        <span class="small-header">{small-header}</span> \r\n      </div>\r\n      <div class="modal-body">\r\n        <div id="device-list" class="list-group">\r\n          <!--<a href="#" v-for="device in foundDevices" v-on:click="select($index)" v-bind:class="{\'connected\':device.state == 2, \'pending\': device.state == 1}" class="list-group-item">\r\n            <span v-if="device.state == 2" class="device-tick glyphicon glyphicon-ok" aria-hidden="true"></span>\r\n            <span class="device-name">{{ device.name }}</span>\r\n            <span class="device-address">{{device.macAddress}}</span>\r\n            <span v-if="device.state == 1" class="device-pending">Initialising...</span>\r\n            <span v-if="device.state == 2" class="device-disconnect glyphicon glyphicon-remove-circle" aria-hidden="true"></span>\r\n          </a>-->\r\n        </div>\r\n      </div>\r\n      <div class="modal-footer">\r\n        <button type="button" class="btn btn-default btn-small btn-close" data-dismiss="modal" aria-label="Close"> Close </button>\r\n      </div>\r\n      </div>\r\n  </div>\r\n</div>\r\n'
});
define("text!partials/_ble-device-item.html", [], function () {
    return '<a href="#" class="list-group-item" data-toggle="tooltip" title="Click to connect/disconnect">\r\n  <span class="device-tick glyphicon glyphicon-ok" aria-hidden="true"></span>\r\n  <span class="device-name">{name}</span>\r\n  <span class="device-address">{address}</span>\r\n  <span class="device-pending">Initialising...</span>\r\n  <span class="device-disconnect glyphicon glyphicon-remove-circle" aria-hidden="true"></span>\r\n</a>\r\n'
});
define("text!partials/_ble-test-dialog.html", [], function () {
    return '<div class="modal fade ble-test-dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">\r\n  <div class="modal-dialog" role="document">\r\n    <div class="modal-content">\r\n      <div class="modal-header">\r\n        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>\r\n        <h4 class="modal-title">Test commands</h4>\r\n      </div>\r\n      <div class="modal-body">\r\n        <div class="device-commands list-group">\r\n          <!--<button v-for="command in deviceData.handler.testCommandNames" v-on:click="executeCommandAt(deviceData.handler, $index)" class="list-group-item">{{command}}</button>-->\r\n        </div>\r\n        <!--<ul class="device-values list-group">\r\n          <li class="list-group-item active">Port values</li>\r\n          !--<li v-for="port in deviceData.handler.state" class="list-group-item">{{port.type}}:{{port.value}}</li>--\r\n        </ul>-->\r\n      </div>\r\n      <div class="modal-footer">\r\n        <button type="button" class="btn btn-default btn-small btn-close" data-dismiss="modal" aria-label="Close"> Close </button>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n'
});
